name: ConsolePlus
version: '1.7'
main: org.linuxfirmware.consolePlus.ConsolePlus
api-version: '1.21'
commands:
  shell:
    description: Manage and execute system commands.
    usage: /shell <run|input|list|stop|env|help> [args]
